title: DataNova Consulting | Self-Hosted Zapier Alternative
description: Replace Zapier and other subscription-based workflow tools with custom, self-hosted solutions tailored to your business — one-time setup fee, no monthly costs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datanovaconsulting.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima - removed to prevent theme CSS conflicts

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - README.md