title: DataNova Consulting | Custom AI Productivity Tools
description: We design AI-powered solutions tailored to your business — automating tasks, optimizing workflows, and eliminating inefficiencies without ongoing subscriptions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datanovaconsulting.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima - removed to prevent theme CSS conflicts

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - README.md